# Generated by Django 3.2.14 on 2022-08-10 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivalapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festival',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='like', to='festivalapp.User'),
        ),
    ]
